# Generated by Django 5.1.15 on 2026-04-28 08:22

from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Periode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.PositiveSmallIntegerField()),
                ('statut', models.CharField(choices=[('OUVERTE', 'Ouverte'), ('VERROUILLEE', 'Verrouillée'), ('CLOTUREE', 'Clôturée')], default='OUVERTE', max_length=20)),
            ],
            options={
                'verbose_name': 'Période',
                'verbose_name_plural': 'Périodes',
                'ordering': ['exercice', 'mois'],
            },
        ),
        migrations.CreateModel(
            name='PieceComptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(blank=True, null=True)),
                ('date_piece', models.DateField()),
                ('date_saisie', models.DateTimeField(auto_now_add=True)),
                ('reference', models.CharField(blank=True, default='', max_length=50)),
                ('libelle', models.CharField(max_length=200)),
                ('statut', models.CharField(choices=[('BROUILLARD', 'Brouillard'), ('VALIDEE', 'Validée'), ('EXTOURNEE', 'Extournée')], default='BROUILLARD', max_length=20)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('total_debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
            ],
            options={
                'verbose_name': 'Pièce comptable',
                'verbose_name_plural': 'Pièces comptables',
                'ordering': ['-date_piece', '-date_saisie'],
            },
        ),
        migrations.CreateModel(
            name='CompteComptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(db_index=True, max_length=20, unique=True)),
                ('libelle', models.CharField(max_length=200)),
                ('classe', models.PositiveSmallIntegerField()),
                ('sens', models.CharField(choices=[('DEBITEUR', 'Débiteur'), ('CREDITEUR', 'Créditeur'), ('MIXTE', 'Mixte')], default='MIXTE', max_length=10)),
                ('collectif_tiers', models.BooleanField(default=False)),
                ('analytique_ok', models.BooleanField(default=False)),
                ('actif', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enfants', to='comptabilite.comptecomptable')),
            ],
            options={
                'verbose_name': 'Compte comptable',
                'verbose_name_plural': 'Plan de comptes',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Exercice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('statut', models.CharField(choices=[('OUVERT', 'Ouvert'), ('EN_COURS_CLOTURE', 'En cours de clôture'), ('CLOTURE', 'Clôturé')], default='OUVERT', max_length=20)),
                ('date_cloture', models.DateTimeField(blank=True, null=True)),
                ('cloture_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercices_clotures', to=settings.AUTH_USER_MODEL)),
                ('exercice_precedent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='suivants', to='comptabilite.exercice')),
            ],
            options={
                'verbose_name': 'Exercice',
                'verbose_name_plural': 'Exercices',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('libelle', models.CharField(max_length=100)),
                ('type_journal', models.CharField(choices=[('ACHATS', 'Achats'), ('VENTES', 'Ventes'), ('BANQUE', 'Banque'), ('CAISSE', 'Caisse'), ('OD', 'Opérations diverses'), ('AN', 'À-nouveaux'), ('PAIE', 'Paie')], max_length=10)),
                ('actif', models.BooleanField(default=True)),
                ('compte_contrepartie', models.ForeignKey(blank=True, help_text='Obligatoire pour BANQUE / CAISSE', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journaux', to='comptabilite.comptecomptable')),
            ],
            options={
                'verbose_name': 'Journal',
                'verbose_name_plural': 'Journaux',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='LigneEcriture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ligne', models.PositiveSmallIntegerField()),
                ('libelle', models.CharField(blank=True, default='', max_length=200)),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('date_echeance', models.DateField(blank=True, null=True)),
                ('date_operation', models.DateField(blank=True, null=True)),
                ('pointee', models.BooleanField(default=False)),
                ('lettre_lettrage', models.CharField(blank=True, db_index=True, default='', max_length=3)),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes', to='comptabilite.comptecomptable')),
            ],
            options={
                'verbose_name': "Ligne d'écriture",
                'verbose_name_plural': "Lignes d'écriture",
                'ordering': ['piece', 'numero_ligne'],
            },
        ),
    ]
