# Generated by Django 5.1.15 on 2026-04-28 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comptabilite', '0001_initial'),
        ('tiers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ligneecriture',
            name='tiers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lignes', to='tiers.tiers'),
        ),
        migrations.AddField(
            model_name='periode',
            name='exercice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodes', to='comptabilite.exercice'),
        ),
        migrations.AddField(
            model_name='piececomptable',
            name='auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pieces_creees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='piececomptable',
            name='exercice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pieces', to='comptabilite.exercice'),
        ),
        migrations.AddField(
            model_name='piececomptable',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pieces', to='comptabilite.journal'),
        ),
        migrations.AddField(
            model_name='piececomptable',
            name='piece_extournee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extournes', to='comptabilite.piececomptable'),
        ),
        migrations.AddField(
            model_name='piececomptable',
            name='validee_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pieces_validees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ligneecriture',
            name='piece',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='comptabilite.piececomptable'),
        ),
        migrations.AddIndex(
            model_name='comptecomptable',
            index=models.Index(fields=['classe'], name='comptabilit_classe_b79402_idx'),
        ),
        migrations.AddIndex(
            model_name='comptecomptable',
            index=models.Index(fields=['collectif_tiers'], name='comptabilit_collect_e9a867_idx'),
        ),
        migrations.AddConstraint(
            model_name='exercice',
            constraint=models.CheckConstraint(condition=models.Q(('date_fin__gt', models.F('date_debut'))), name='exercice_dates_coherentes'),
        ),
        migrations.AddConstraint(
            model_name='periode',
            constraint=models.UniqueConstraint(fields=('exercice', 'mois'), name='periode_unique_par_exercice'),
        ),
        migrations.AddConstraint(
            model_name='periode',
            constraint=models.CheckConstraint(condition=models.Q(('mois__gte', 1), ('mois__lte', 12)), name='periode_mois_valide'),
        ),
        migrations.AddIndex(
            model_name='piececomptable',
            index=models.Index(fields=['exercice', 'statut'], name='comptabilit_exercic_15bf99_idx'),
        ),
        migrations.AddIndex(
            model_name='piececomptable',
            index=models.Index(fields=['date_piece'], name='comptabilit_date_pi_478295_idx'),
        ),
        migrations.AddConstraint(
            model_name='piececomptable',
            constraint=models.CheckConstraint(condition=models.Q(('statut', 'BROUILLARD'), ('total_debit', models.F('total_credit')), _connector='OR'), name='piece_equilibree_si_validee'),
        ),
        migrations.AddConstraint(
            model_name='piececomptable',
            constraint=models.UniqueConstraint(condition=models.Q(('numero__isnull', False)), fields=('journal', 'exercice', 'numero'), name='piece_numero_unique_par_journal_exercice'),
        ),
        migrations.AddIndex(
            model_name='ligneecriture',
            index=models.Index(fields=['compte', 'date_operation'], name='comptabilit_compte__04b0ee_idx'),
        ),
        migrations.AddConstraint(
            model_name='ligneecriture',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('debit__gt', 0), ('credit', 0)), models.Q(('debit', 0), ('credit__gt', 0)), _connector='OR'), name='ligne_debit_xor_credit'),
        ),
        migrations.AddConstraint(
            model_name='ligneecriture',
            constraint=models.UniqueConstraint(fields=('piece', 'numero_ligne'), name='ligne_numero_unique_dans_piece'),
        ),
    ]
