# Generated by Django 5.1.15 on 2026-04-28 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comptabilite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tiers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_tiers', models.CharField(choices=[('CLIENT', 'Client'), ('FOURNISSEUR', 'Fournisseur'), ('DIVERS', 'Divers')], max_length=20)),
                ('code_auxiliaire', models.CharField(db_index=True, max_length=10, unique=True)),
                ('raison_sociale', models.CharField(max_length=200)),
                ('forme_juridique', models.CharField(blank=True, default='', max_length=50)),
                ('identifiant_fiscal', models.CharField(blank=True, default='', max_length=50)),
                ('adresse', models.CharField(blank=True, default='', max_length=200)),
                ('cp', models.CharField(blank=True, default='', max_length=20)),
                ('ville', models.CharField(blank=True, default='', max_length=100)),
                ('pays', models.CharField(default='BJ', max_length=2)),
                ('contacts', models.JSONField(blank=True, default=list)),
                ('iban', models.CharField(blank=True, default='', max_length=34)),
                ('bic', models.CharField(blank=True, default='', max_length=11)),
                ('delai_reglement_jours', models.PositiveIntegerField(default=30)),
                ('mode_reglement', models.CharField(choices=[('VIREMENT', 'Virement'), ('CHEQUE', 'Chèque'), ('ESPECES', 'Espèces'), ('PRELEVEMENT', 'Prélèvement')], default='VIREMENT', max_length=20)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('compte_collectif', models.ForeignKey(limit_choices_to={'collectif_tiers': True}, on_delete=django.db.models.deletion.PROTECT, related_name='tiers', to='comptabilite.comptecomptable')),
            ],
            options={
                'verbose_name': 'Tiers',
                'verbose_name_plural': 'Tiers',
                'ordering': ['raison_sociale'],
                'indexes': [models.Index(fields=['raison_sociale'], name='tiers_tiers_raison__0abe7d_idx'), models.Index(fields=['type_tiers'], name='tiers_tiers_type_ti_7898b4_idx')],
            },
        ),
    ]
