# Generated by Django 5.1.15 on 2026-06-08 09:24

from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comptabilite', '0003_pg_triggers'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieImmobilisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('libelle', models.CharField(max_length=200)),
                ('duree_defaut', models.PositiveSmallIntegerField()),
                ('mode_defaut', models.CharField(choices=[('LINEAIRE', 'Linéaire'), ('DEGRESSIF', 'Dégressif')], default='LINEAIRE', max_length=10)),
                ('actif', models.BooleanField(default=True)),
                ('compte_amortissement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categories_amort', to='comptabilite.comptecomptable')),
                ('compte_dotation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categories_dotation', to='comptabilite.comptecomptable')),
                ('compte_immo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categories_immo', to='comptabilite.comptecomptable')),
            ],
            options={
                'verbose_name': "Catégorie d'immobilisation",
                'verbose_name_plural': "Catégories d'immobilisation",
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Immobilisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=12, unique=True)),
                ('designation', models.CharField(max_length=200)),
                ('date_acquisition', models.DateField()),
                ('date_mise_service', models.DateField()),
                ('cout_acquisition', models.DecimalField(decimal_places=2, max_digits=15)),
                ('valeur_residuelle', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('duree', models.PositiveSmallIntegerField(help_text="Durée d'amortissement en années")),
                ('mode_amortissement', models.CharField(choices=[('LINEAIRE', 'Linéaire'), ('DEGRESSIF', 'Dégressif')], default='LINEAIRE', max_length=10)),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('EN_SERVICE', 'En service'), ('CEDEE', 'Cédée'), ('REBUT', 'Mise au rebut')], default='EN_COURS', max_length=12)),
                ('date_cession', models.DateField(blank=True, null=True)),
                ('prix_cession', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='immobilisations', to='immobilisations.categorieimmobilisation')),
                ('compte_amortissement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='immos_amort', to='comptabilite.comptecomptable')),
                ('compte_dotation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='immos_dotation', to='comptabilite.comptecomptable')),
                ('compte_immo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='immos', to='comptabilite.comptecomptable')),
                ('piece_cession', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cessions_immo', to='comptabilite.piececomptable')),
            ],
            options={
                'verbose_name': 'Immobilisation',
                'verbose_name_plural': 'Immobilisations',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Dotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveSmallIntegerField()),
                ('mois', models.PositiveSmallIntegerField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cumul', models.DecimalField(decimal_places=2, max_digits=15)),
                ('vnc', models.DecimalField(decimal_places=2, max_digits=15)),
                ('statut', models.CharField(choices=[('PREVUE', 'Prévue'), ('COMPTABILISEE', 'Comptabilisée')], default='PREVUE', max_length=15)),
                ('piece_generee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dotations', to='comptabilite.piececomptable')),
                ('immobilisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dotations', to='immobilisations.immobilisation')),
            ],
            options={
                'verbose_name': 'Dotation aux amortissements',
                'verbose_name_plural': 'Dotations aux amortissements',
                'ordering': ['immobilisation', 'annee', 'mois'],
            },
        ),
        migrations.AddIndex(
            model_name='immobilisation',
            index=models.Index(fields=['statut'], name='immobilisat_statut_8a24a3_idx'),
        ),
        migrations.AddConstraint(
            model_name='immobilisation',
            constraint=models.CheckConstraint(condition=models.Q(('cout_acquisition__gt', 0)), name='immo_cout_positif'),
        ),
        migrations.AddConstraint(
            model_name='immobilisation',
            constraint=models.CheckConstraint(condition=models.Q(('duree__gte', 1)), name='immo_duree_min'),
        ),
        migrations.AddConstraint(
            model_name='immobilisation',
            constraint=models.CheckConstraint(condition=models.Q(('valeur_residuelle__gte', 0), ('valeur_residuelle__lt', models.F('cout_acquisition'))), name='immo_valeur_residuelle_coherente'),
        ),
        migrations.AddIndex(
            model_name='dotation',
            index=models.Index(fields=['annee', 'mois', 'statut'], name='immobilisat_annee_b28a48_idx'),
        ),
        migrations.AddConstraint(
            model_name='dotation',
            constraint=models.UniqueConstraint(fields=('immobilisation', 'annee', 'mois'), name='dotation_unique_periode'),
        ),
        migrations.AddConstraint(
            model_name='dotation',
            constraint=models.CheckConstraint(condition=models.Q(('mois__gte', 1), ('mois__lte', 12)), name='dotation_mois_valide'),
        ),
        migrations.AddConstraint(
            model_name='dotation',
            constraint=models.CheckConstraint(condition=models.Q(('montant__gte', 0)), name='dotation_montant_positif'),
        ),
    ]
