# Generated by Django 5.1.15 on 2026-06-18 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0004_pg_triggers_r9'),
        ('immobilisations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationCessionImmo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actif', models.BooleanField(default=True)),
                ('compte_creance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='config_cession_creance', to='comptabilite.comptecomptable')),
                ('compte_produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='config_cession_produit', to='comptabilite.comptecomptable')),
                ('compte_valeur_comptable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='config_cession_vc', to='comptabilite.comptecomptable')),
            ],
            options={
                'verbose_name': 'Configuration cession immobilisation',
                'verbose_name_plural': 'Configurations cession immobilisation',
            },
        ),
    ]
