# Generated by Django 5.1.15 on 2026-04-21 17:07

import django.core.validators
import django.db.models.deletion
import django_tenants.postgresql_backend.base
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('referentiels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Societe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('code', models.CharField(max_length=20, unique=True)),
                ('raison_sociale', models.CharField(max_length=200)),
                ('pays', models.CharField(choices=[('BJ', 'Bénin'), ('CI', "Côte d'Ivoire"), ('SN', 'Sénégal'), ('TG', 'Togo'), ('CM', 'Cameroun'), ('FR', 'France'), ('BE', 'Belgique'), ('TN', 'Tunisie')], db_index=True, max_length=5)),
                ('devise', models.CharField(choices=[('XOF', 'Franc CFA BCEAO'), ('XAF', 'Franc CFA BEAC'), ('EUR', 'Euro'), ('TND', 'Dinar Tunisien'), ('USD', 'Dollar US')], default='XOF', max_length=5)),
                ('referentiel', models.CharField(choices=[('SYSCOHADA', 'SYSCOHADA 2017'), ('PCG_FR', 'PCG France'), ('PCMN_BE', 'PCMN Belgique'), ('PCT_TN', 'PCT Tunisie')], default='SYSCOHADA', max_length=20)),
                ('ifu_siret', models.CharField(blank=True, max_length=50)),
                ('exercice_debut_mois', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('statut', models.CharField(choices=[('active', 'Active'), ('suspendue', 'Suspendue'), ('archivee', 'Archivée')], default='active', max_length=20)),
                ('plan_comptes_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='societes', to='referentiels.plancomptabletype')),
            ],
            options={
                'verbose_name': 'Société',
                'verbose_name_plural': 'Sociétés',
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenants.societe')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
