# Generated by Django 5.1.15 on 2026-06-08 13:54

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comptabilite', '0004_pg_triggers_r9'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationTVA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=200)),
                ('periodicite', models.CharField(choices=[('MENSUELLE', 'Mensuelle'), ('TRIMESTRIELLE', 'Trimestrielle')], default='MENSUELLE', max_length=15)),
                ('actif', models.BooleanField(default=True)),
                ('compte_credit_tva', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='config_tva_credit', to='comptabilite.comptecomptable')),
                ('compte_tva_due', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='config_tva_due', to='comptabilite.comptecomptable')),
                ('comptes_collectee', models.ManyToManyField(related_name='config_tva_collectee', to='comptabilite.comptecomptable')),
                ('comptes_deductible', models.ManyToManyField(related_name='config_tva_deductible', to='comptabilite.comptecomptable')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='config_tva', to='comptabilite.journal')),
            ],
            options={
                'verbose_name': 'Configuration TVA',
                'verbose_name_plural': 'Configurations TVA',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='DeclarationTVA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveSmallIntegerField()),
                ('periode_num', models.PositiveSmallIntegerField(help_text='Mois (1-12) ou trimestre (1-4)')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('tva_collectee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('tva_deductible', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('tva_nette', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('VALIDEE', 'Validée')], default='BROUILLON', max_length=10)),
                ('bordereau', models.FileField(blank=True, null=True, upload_to='bordereaux_tva/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='declarations', to='fiscal.configurationtva')),
                ('piece_liquidation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='declarations_tva', to='comptabilite.piececomptable')),
            ],
            options={
                'verbose_name': 'Déclaration TVA',
                'verbose_name_plural': 'Déclarations TVA',
                'ordering': ['-annee', '-periode_num'],
                'constraints': [models.UniqueConstraint(fields=('configuration', 'annee', 'periode_num'), name='declaration_tva_unique_periode')],
            },
        ),
    ]
