# Generated by Django 5.1.15 on 2026-06-18 08:29

from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0004_pg_triggers_r9'),
        ('fiscal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationIS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=200)),
                ('taux', models.DecimalField(decimal_places=2, help_text='Pourcentage, ex. 30.00', max_digits=5)),
                ('actif', models.BooleanField(default=True)),
                ('compte_charge_impot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='config_is_charge', to='comptabilite.comptecomptable')),
                ('compte_dette_impot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='config_is_dette', to='comptabilite.comptecomptable')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='config_is', to='comptabilite.journal')),
            ],
            options={
                'verbose_name': 'Configuration IS',
                'verbose_name_plural': 'Configurations IS',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='DeclarationIS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultat_comptable', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_reintegrations', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('resultat_fiscal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('impot', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('VALIDEE', 'Validée')], default='BROUILLON', max_length=10)),
                ('bordereau', models.FileField(blank=True, null=True, upload_to='bordereaux_is/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='declarations', to='fiscal.configurationis')),
                ('exercice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='declarations_is', to='comptabilite.exercice')),
                ('piece_imposition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='declarations_is', to='comptabilite.piececomptable')),
            ],
            options={
                'verbose_name': 'Déclaration IS',
                'verbose_name_plural': 'Déclarations IS',
                'ordering': ['-exercice'],
            },
        ),
        migrations.CreateModel(
            name='RetraitementFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=200)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15)),
                ('sens', models.CharField(choices=[('REINTEGRATION', 'Réintégration'), ('DEDUCTION', 'Déduction')], max_length=15)),
                ('declaration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retraitements', to='fiscal.declarationis')),
            ],
            options={
                'verbose_name': 'Retraitement fiscal',
                'verbose_name_plural': 'Retraitements fiscaux',
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='declarationis',
            constraint=models.UniqueConstraint(fields=('configuration', 'exercice'), name='declaration_is_unique_exercice'),
        ),
    ]
