# Generated by Django 5.1.15 on 2026-06-18 09:22

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0004_pg_triggers_r9'),
        ('fiscal', '0002_configurationis_declarationis_retraitementfiscal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationAIB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=200)),
                ('taux', models.DecimalField(decimal_places=2, help_text='Pourcentage, ex. 1.00', max_digits=5)),
                ('actif', models.BooleanField(default=True)),
                ('compte_aib', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='config_aib_acompte', to='comptabilite.comptecomptable')),
                ('compte_tresorerie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='config_aib_tresorerie', to='comptabilite.comptecomptable')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='config_aib', to='comptabilite.journal')),
            ],
            options={
                'verbose_name': 'Configuration AIB',
                'verbose_name_plural': 'Configurations AIB',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='DeclarationAIB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveSmallIntegerField()),
                ('periode_num', models.PositiveSmallIntegerField(help_text='Mois (1-12)')),
                ('base_imposable', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('montant_aib', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('VALIDEE', 'Validée')], default='BROUILLON', max_length=10)),
                ('bordereau', models.FileField(blank=True, null=True, upload_to='bordereaux_aib/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='declarations', to='fiscal.configurationaib')),
                ('piece', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='declarations_aib', to='comptabilite.piececomptable')),
            ],
            options={
                'verbose_name': 'Déclaration AIB',
                'verbose_name_plural': 'Déclarations AIB',
                'ordering': ['-annee', '-periode_num'],
                'constraints': [models.UniqueConstraint(fields=('configuration', 'annee', 'periode_num'), name='declaration_aib_unique_periode')],
            },
        ),
    ]
