# Generated by Django 5.1.15 on 2026-04-21 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JournalAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horodatage', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('utilisateur_id', models.IntegerField()),
                ('utilisateur_email', models.EmailField(max_length=254)),
                ('action', models.CharField(choices=[('INSERT', 'Insertion'), ('UPDATE', 'Modification'), ('DELETE', 'Suppression'), ('VALIDATE', 'Validation'), ('CLOSE', 'Clôture'), ('TEST', 'Test')], max_length=20)),
                ('table_cible', models.CharField(max_length=100)),
                ('enregistrement_id', models.BigIntegerField()),
                ('valeurs_avant', models.JSONField(blank=True, null=True)),
                ('valeurs_apres', models.JSONField(blank=True, null=True)),
                ('ip_adresse', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': "Entrée d'audit",
                'verbose_name_plural': "Journal d'audit",
                'ordering': ['-horodatage'],
            },
        ),
    ]
