# Generated by Django 5.1.15 on 2026-04-21 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlanComptableType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('libelle', models.CharField(max_length=200)),
                ('pays_applicable', models.CharField(max_length=50)),
                ('version', models.CharField(max_length=20)),
                ('date_effet', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Plan comptable type',
                'verbose_name_plural': 'Plans comptables types',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CompteType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('libelle', models.CharField(max_length=200)),
                ('classe', models.PositiveSmallIntegerField()),
                ('sens', models.CharField(choices=[('debiteur', 'Débiteur'), ('crediteur', 'Créditeur'), ('mixte', 'Mixte')], max_length=10)),
                ('collectif_tiers', models.BooleanField(default=False)),
                ('analytique_ok', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enfants', to='referentiels.comptetype')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comptes', to='referentiels.plancomptabletype')),
            ],
            options={
                'verbose_name': 'Compte type',
                'verbose_name_plural': 'Comptes types',
                'ordering': ['numero'],
                'unique_together': {('plan', 'numero')},
            },
        ),
    ]
