# Generated by Django 5.1.15 on 2026-04-28 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_export', models.CharField(choices=[('FEC', 'FEC (texte BOI)'), ('BALANCE_XLSX', 'Balance Excel'), ('GL_XLSX', 'Grand livre Excel'), ('JOURNAL_XLSX', 'Journal Excel'), ('BALANCE_PDF', 'Balance PDF'), ('BILAN_PDF', 'Bilan PDF'), ('CR_PDF', 'Compte de résultat PDF')], max_length=30)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='exports/')),
                ('parametres', models.JSONField(blank=True, default=dict)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_COURS', 'En cours'), ('TERMINE', 'Terminé'), ('ERREUR', 'Erreur')], default='EN_ATTENTE', max_length=20)),
                ('erreur', models.TextField(blank=True, default='')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Job d'export",
                'verbose_name_plural': "Jobs d'export",
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='imports/')),
                ('modele', models.CharField(choices=[('ACHATS', 'Journal Achats'), ('VENTES', 'Journal Ventes'), ('OD', 'Opérations diverses')], max_length=20)),
                ('journal_code', models.CharField(max_length=10)),
                ('exercice_code', models.CharField(max_length=20)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_COURS', 'En cours'), ('TERMINE', 'Terminé'), ('ERREUR', 'Erreur')], default='EN_ATTENTE', max_length=20)),
                ('rapport', models.JSONField(blank=True, default=dict)),
                ('nb_lignes_traitees', models.PositiveIntegerField(default=0)),
                ('nb_pieces_creees', models.PositiveIntegerField(default=0)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Job d'import",
                'verbose_name_plural': "Jobs d'import",
                'ordering': ['-date_creation'],
            },
        ),
    ]
