# Generated by Django 5.1.15 on 2026-06-08 10:27

from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comptabilite', '0003_pg_triggers'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompteBancaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=200)),
                ('banque_nom', models.CharField(blank=True, default='', max_length=100)),
                ('iban', models.CharField(blank=True, default='', max_length=34)),
                ('bic', models.CharField(blank=True, default='', max_length=11)),
                ('devise', models.CharField(default='XOF', max_length=3)),
                ('solde_initial', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('actif', models.BooleanField(default=True)),
                ('compte_comptable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comptes_bancaires', to='comptabilite.comptecomptable')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comptes_bancaires', to='comptabilite.journal')),
            ],
            options={
                'verbose_name': 'Compte bancaire',
                'verbose_name_plural': 'Comptes bancaires',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='ReleveBancaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('solde_initial', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('solde_final', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('RAPPROCHE', 'Rapproché'), ('CLOS', 'Clos')], default='EN_COURS', max_length=10)),
                ('fichier_source', models.FileField(blank=True, null=True, upload_to='releves/')),
                ('date_import', models.DateTimeField(auto_now_add=True)),
                ('compte_bancaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='releves', to='banque.comptebancaire')),
            ],
            options={
                'verbose_name': 'Relevé bancaire',
                'verbose_name_plural': 'Relevés bancaires',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='LigneReleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_operation', models.DateField()),
                ('libelle', models.CharField(max_length=200)),
                ('montant', models.DecimalField(decimal_places=2, help_text='Signé : + encaissement / - décaissement', max_digits=15)),
                ('reference_banque', models.CharField(blank=True, default='', max_length=50)),
                ('statut', models.CharField(choices=[('NON_POINTEE', 'Non pointée'), ('POINTEE_AUTO', 'Pointée (auto)'), ('POINTEE_MANUEL', 'Pointée (manuel)')], default='NON_POINTEE', max_length=15)),
                ('ligne_ecriture_pointee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_releve', to='comptabilite.ligneecriture')),
                ('releve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='banque.relevebancaire')),
            ],
            options={
                'verbose_name': 'Ligne de relevé',
                'verbose_name_plural': 'Lignes de relevé',
                'ordering': ['releve', 'date_operation'],
            },
        ),
        migrations.AddConstraint(
            model_name='relevebancaire',
            constraint=models.CheckConstraint(condition=models.Q(('date_fin__gte', models.F('date_debut'))), name='releve_dates_coherentes'),
        ),
        migrations.AddIndex(
            model_name='lignereleve',
            index=models.Index(fields=['releve', 'statut'], name='banque_lign_releve__f99a8f_idx'),
        ),
        migrations.AddConstraint(
            model_name='lignereleve',
            constraint=models.CheckConstraint(condition=models.Q(('montant', 0), _negated=True), name='ligne_releve_montant_non_nul'),
        ),
    ]
